version: '3.8'

services:
    prod:
        container_name: outreach_app
        image: shelterapp/outreach_app:$VERSION
        ports:
            - 3000:3000
        networks:
            - nesjs-network
        restart: unless-stopped

networks:
    nesjs-network: